name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate .env file
      - name: Generate .env file
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "GENIUS_ACCESS_TOKEN=${{ secrets.GENIUS_ACCESS_TOKEN }}" >> .env

      # Decode cookies.txt from GitHub Secrets
      - name: Decode cookies.txt
        env:
          COOKIES_TXT: ${{ secrets.YOUTUBE_COOKIES }}
        run: |
          echo "$COOKIES_TXT" | base64 --decode > cookies.txt

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t gomu-discord-bot .

      # Save Docker image as a tarball
      - name: Save Docker image
        run: docker save gomu-discord-bot > gomu-discord-bot.tar

      # Copy Docker image, .env, and cookies.txt to EC2
      - name: Copy files to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem gomu-discord-bot.tar .env cookies.txt ubuntu@$EC2_IP:/home/ubuntu/

      # SSH into EC2 and deploy
      - name: Deploy Docker container
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_IP << EOF
          docker stop gomu-discord-bot || true
          docker rm gomu-discord-bot || true
          docker load < /home/ubuntu/gomu-discord-bot.tar
          docker run -d --restart=always --name gomu-discord-bot --env-file /home/ubuntu/.env -v /home/ubuntu/cookies.txt:/app/cookies.txt gomu-discord-bot
          EOF
